apiVersion: v2
description: A Helm chart for Tekton Pipelines
name: tekton-pipeline
version: 1.9.1
appVersion: 1.9.1
icon: https://avatars2.githubusercontent.com/u/47602533
home: https://github.com/cdfoundation/tekton-helm-chart
